// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component Button {
  in property <string> text;
  in property <color> background: #7678ed;
  in property <bool> enabled: true;
  callback clicked();

  Rectangle {
    background: root.background;
    border-color: rgba(24, 24, 32, 0.75);
    border-radius: 8px;
    border-width: 1px;
    opacity: root.enabled ? 100% : 50%;
    drop-shadow-blur: 8px;
    drop-shadow-color: rgba(0, 0, 0, 0.15);
    drop-shadow-offset-y: 4px;

    Text {
      text: root.text;
      color: white;
      font-family: "Inter";
      font-size: 14px;
      font-weight: 600;
      horizontal-alignment: center;
      vertical-alignment: center;
    }

    TouchArea {
      enabled: root.enabled;
      mouse-cursor: pointer;
      clicked => { root.clicked(); }
    }
  }
}
