// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component CheckBox {
  in property <string> text;
  in-out property <bool> enabled;
  callback toggled();

  min-height: 22px;

  states [
    hover_unchecked when touch_area.has-hover && !root.enabled: {
      checkbox_rect.background: #45475a;
    }

    hover_checked when touch_area.has-hover && root.enabled: {
      checkbox_rect.background: #5d5fd1;
    }
  ]

  HorizontalLayout {
    spacing: 8px;
    alignment: center;

    Rectangle {
      width: 18px;
      height: 18px;

      checkbox_rect := Rectangle {
        width: 100%;
        height: 100%;
        background: root.enabled ? #7678ed : transparent;
        border-radius: 3px;
        border-width: 1px;
        border-color: #6c7086;

        animate background { duration: 150ms; easing: ease-out; }
        animate border-color { duration: 150ms; easing: ease-out; }

        states [
          checked when root.enabled: {
            border-color: #7678ed4d;
          }
        ]

        if root.enabled: Image {
          width: 14px;
          height: 14px;
          source: @image-url("../assets/checkmark.svg");
          colorize: white;
        }
      }
    }

    Text {
      y: -2.5px;
      text: root.text;
      color: #cdd6f4;
      font-family: "Inter";
      font-size: 14px;
      vertical-alignment: center;
    }
  }

  touch_area := TouchArea {
    clicked => {
      root.enabled = !root.enabled;
      root.toggled();
    }
  }
}
