// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { ThemeLogic } from "../logic/theme.slint";

export component CheckBox {
  in property <string> text;
  in-out property <bool> enabled;
  callback toggled();

  min-height: 22px;

  states [
    hover_unchecked when touch_area.has-hover && !root.enabled: {
      checkbox_rect.background: ThemeLogic.colors.secondary_hover;
    }

    hover_checked when touch_area.has-hover && root.enabled: {
      checkbox_rect.background: ThemeLogic.colors.primary_hover;
    }
  ]

  HorizontalLayout {
    spacing: 8px;
    alignment: center;

    Rectangle {
      width: 18px;
      height: 18px;

      checkbox_rect := Rectangle {
        width: 100%;
        height: 100%;
        background: root.enabled ? ThemeLogic.colors.primary : transparent;
        border-radius: 3px;
        border-width: 1px;
        border-color: ThemeLogic.colors.check_box_border;

        animate background { duration: 150ms; easing: ease-out; }
        animate border-color { duration: 150ms; easing: ease-out; }

        states [
          checked when root.enabled: {
            border-color: ThemeLogic.colors.check_box_border_active;
          }
        ]

        if root.enabled: Image {
          width: 14px;
          height: 14px;
          source: @image-url("../assets/checkmark.svg");
          colorize: ThemeLogic.colors.text_primary;
        }
      }
    }

    Text {
      y: -2.5px;
      text: root.text;
      color: ThemeLogic.colors.text_secondary;
      font-family: "Inter";
      font-size: 14px;
      vertical-alignment: center;
    }
  }

  touch_area := TouchArea {
    clicked => {
      root.enabled = !root.enabled;
      root.toggled();
    }
  }
}
