// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { UiGame } from "../structs/ui_game.slint";

export component GameCard inherits Rectangle {
  in property <UiGame> game;
  property <bool> selected: true;

  background: #1e1e2e;
  border-radius: 20px;

  HorizontalLayout {
    padding: 12px;
    spacing: 8px;

    Rectangle {
      width: 24px;
      height: 24px;

      icon_container := Rectangle {
        background: rgba(47, 47, 70, 0.75);
        border-color: rgba(24, 24, 32, 0.25);
        border-radius: 2px;
        border-width: 1px;
      }

      Image {
        source: @image-url("../assets/check.svg");
        opacity: root.selected ? 100% : 10%;
        x: 0;
      }
    }

    HorizontalLayout {
      alignment: start;
      spacing: 4px;

      Text {
        text: game.name;
        font-size: 16px;
        color: white;
        overflow: elide;
        vertical-alignment: center;
      }

      Text {
        y: 1px;
        text: "(" + game.source + ")";
        opacity: 25%;
        font-size: 10px;
        vertical-alignment: center;
      }
    }

    Text {
      text: game.backup_size;
      font-size: 14px;
      color: #a0a0a0;
      horizontal-alignment: right;
      vertical-alignment: center;
    }
  }

  TouchArea {
    clicked => { root.selected = !root.selected; }
  }
}
