// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { ThemeLogic } from "../logic/theme.slint";
import { UiGame } from "../structs/ui_game.slint";

export component GameCard inherits Rectangle {
  in property <UiGame> game;
  callback clicked <=> touch_area.clicked;

  background: ThemeLogic.colors.surface;
  border-radius: 20px;
  accessible-role: checkbox;
  accessible-checkable: true;
  accessible-checked: root.game.selected;
  accessible-action-default => clicked();

  HorizontalLayout {
    padding: 12px;
    spacing: 8px;

    Rectangle {
      width: 24px;
      height: 24px;

      icon_container := Rectangle {
        background: ThemeLogic.colors.surface_variant;
        border-color: ThemeLogic.colors.surface_border;
        border-radius: 2px;
        border-width: 1px;
      }

      Image {
        x: 0;
        source: @image-url("../assets/check.svg");
        opacity: root.game.selected ? 100% : 10%;

        animate opacity { duration: 150ms; easing: ease-out; }
      }
    }

    HorizontalLayout {
      spacing: 4px;
      alignment: start;

      Text {
        text: game.name;
        color: ThemeLogic.colors.text_primary;
        font-family: "Inter";
        font-size: 16px;
        overflow: elide;
        vertical-alignment: center;
      }

      Text {
        y: 1px;
        text: "(" + game.source + ")";
        opacity: 25%;
        font-family: "Inter";
        font-size: 10px;
        vertical-alignment: center;
      }
    }

    Text {
      text: root.game.backup_size;
      color: ThemeLogic.colors.text_muted;
      font-family: "Inter";
      font-size: 14px;
      horizontal-alignment: right;
      vertical-alignment: center;
    }
  }

  touch_area := TouchArea { mouse-cursor: pointer; }
}
