// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component NavItem inherits Rectangle {
  in property <string> text;
  in property <bool> active;
  callback clicked();

  border-radius: 4px;
  background: root.active ? #7c7cff : #2f2f49;
  height: 40px;

  Text {
    text: root.text;
    color: white;
    font-family: "Inter";
    font-weight: root.active ? 700 : 400;
    opacity: root.active ? 100% : 50%;
  }

  touch_area := TouchArea {
    mouse-cursor: pointer;
    clicked => { root.clicked() }
  }

  states [
    hover when touch_area.has-hover: {
      background: root.active ? #5656bc : #3e3e5e;
      in { animate background { duration: 150ms; } }
      out { animate background { duration: 150ms; } }
    }
  ]
}
