// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { ThemeLogic } from "../logic/theme.slint";

export component NavItem inherits Rectangle {
  in property <string> text;
  in property <bool> active;
  in property <image> icon;
  callback clicked <=> touch_area.clicked;

  height: 40px;
  background: ThemeLogic.colors.primary_variant;
  opacity: root.active ? 100% : 50%;
  border-color: ThemeLogic.colors.border;
  border-radius: 4px;
  border-width: 1px;
  drop-shadow-blur: 8px;
  drop-shadow-color: ThemeLogic.colors.surface_shadow;
  drop-shadow-offset-y: 4px;
  accessible-role: button;
  accessible-action-default => clicked();

  icon_container := Rectangle {
    x: 0;
    width: 40px;
    height: 40px;
    background: ThemeLogic.colors.primary_active;
    opacity: root.active ? 25% : 50%;
    border-color: ThemeLogic.colors.surface_border_alt;
    border-radius: 3px;
    border-width: 1px;
  }

  Image {
    x: (icon_container.width - self.width) / 2;
    y: (icon_container.height - self.height) / 2;
    source: root.icon;
    opacity: root.active ? 100% : 50%;
  }

  Text {
    x: icon_container.width;
    width: parent.width - icon_container.width;
    text: root.text;
    color: ThemeLogic.colors.text_primary;
    opacity: root.active ? 100% : 50%;
    font-family: "Inter";
    font-weight: root.active ? 700 : 400;
    horizontal-alignment: center;
    vertical-alignment: center;
  }

  touch_area := TouchArea {
    mouse-cursor: pointer;
  }

  states [
   hover when !root.active && touch_area.has-hover: {
     opacity: 75%;
     in { animate opacity { duration: 150ms; } }
     out { animate opacity { duration: 150ms; } }
   }
  ]
}
