// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component NavItem inherits Rectangle {
  in property <string> text;
  in property <bool> active;
  in property <image> icon;
  callback clicked <=> touch_area.clicked;

  height: 40px;

  background: #7c7cff;
  border-color: rgba(24, 24, 32, 0.75);
  border-radius: 4px;
  border-width: 1px;
  opacity: root.active ? 100% : 50%;

  drop-shadow-blur: 8px;
  drop-shadow-color: rgba(0, 0, 0, 0.15);
  drop-shadow-offset-y: 4px;

  icon_container := Rectangle {
    width: 40px;
    height: 40px;
    x: 0;

    background: #43438B;
    border-color: rgba(24, 24, 32, 0.5);
    border-width: 1px;
    border-radius: 3px;
    opacity: root.active ? 25% : 50%;
  }

  Image {
    source: root.icon;
    x: (icon_container.width - self.width) / 2;
    y: (icon_container.height - self.height) / 2;
    opacity: root.active ? 100% : 50%;
  }

  Text {
    text: root.text;
    color: white;
    font-family: "Inter";
    font-weight: root.active ? 700 : 400;
    opacity: root.active ? 100% : 50%;
    horizontal-alignment: center;
    vertical-alignment: center;
    width: parent.width - icon_container.width;
    x: icon_container.width;
  }

  touch_area := TouchArea {
    mouse-cursor: pointer;
  }

  states [
   hover when !root.active && touch_area.has-hover: {
     opacity: 75%;
     in { animate opacity { duration: 150ms; } }
     out { animate opacity { duration: 150ms; } }
   }
  ]
}
