// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export enum NotificationType {
  SUCCESS,
  ERROR,
  INFO,
  WARNING
}

export component Notification inherits Rectangle {
  in property <string> message;
  in property <NotificationType> notification_type: NotificationType.INFO;
  in property <duration> show_duration: 2500ms;
  in property <length> target_x;
  callback closed <=> close_timer.triggered;

  width: notification_layout.preferred-width + 24px;
  height: notification_layout.preferred-height + 16px;
  border-radius: 8px;
  background: #1e1e2e;
  drop-shadow-blur: 8px;
  drop-shadow-color: rgba(0, 0, 0, 0.15);
  drop-shadow-offset-y: 4px;

  private property <bool> animated_in: false;
  private property <bool> should_close: false;
  private property <image> icon: notification-type == NotificationType.SUCCESS ? @image-url("../assets/check.svg") :
                                 notification-type == NotificationType.ERROR ? @image-url("../assets/cancel.svg") :
                                 notification-type == NotificationType.WARNING ? @image-url("../assets/warning.svg") :
                                 @image-url("../assets/info.svg");

  animate x { duration: 225ms; easing: ease-out; }
  x: animated_in ? target_x : target_x + self.width + 20px;

  Timer {
    running: parent.visible && !root.should_close;
    interval: root.show_duration;
    triggered() => {
      root.should_close = true;
      root.animated_in = false;
    }
  }

  close_timer := Timer {
    running: root.should_close;
    interval: 250ms;
  }

  changed visible => {
    if (self.visible) {
      animated_in = true;
      should_close = false;
    }
  }

  notification_layout := HorizontalLayout {
    spacing: 6px;
    alignment: center;

    Image {
      source: root.icon;
      vertical-alignment: center;
    }

    Text {
      text: root.message;
      color: white;
      font-family: "Inter";
      font-size: 14px;
      font-weight: 500;
      vertical-alignment: center;
    }
  }
}
