// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component SearchBar {
  in property <string> placeholder_text;
  out property <bool> has_focus: input.has-focus;
  out property <string> text: input.text;
  callback changed(string);

  min-height: 30px;
  min-width: 100px;
  horizontal-stretch: 1;

  Rectangle {
    border-radius: 10px;
    border-width: 1px;
    border-color: root.has_focus ? #27273a : #18182040;
    background: #1e1e2e;
    width: 100%;
    height: 100%;

    HorizontalLayout {
      padding: 5px;
      spacing: 5px;

      Image {
        source: @image-url("../assets/search.svg");
        opacity: 75%;
      }

      input := TextInput {
        horizontal-stretch: 1;
        single-line: true;
        font-family: "Inter";
        font-size: 14px;
        font-weight: 400;
        color: white;
        opacity: 65%;
        vertical-alignment: center;

        if (self.text == ""): Text {
          text: root.placeholder_text;
          color: #ffffff80;
          font-family: "Inter";
          font-size: 14px;
          font-weight: 400;
          opacity: 50%;
        }

        edited => { root.changed(self.text); }
      }
    }
  }
}
