// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { ThemeLogic } from "../logic/theme.slint";

export component TextLabel inherits Rectangle {
  in property <string> text;

  background: ThemeLogic.colors.surface;
  border-radius: 4px;
  border-width: 1px;
  border-color: ThemeLogic.colors.surface_border;
  drop-shadow-blur: 8px;
  drop-shadow-color: ThemeLogic.colors.surface_shadow;
  drop-shadow-offset-y: 4px;

  HorizontalLayout {
    spacing: 8px;
    padding-left: 12px;
    padding-right: 12px;

    Text {
      text: root.text;
      color: ThemeLogic.colors.text_primary;
      opacity: 65%;
      font-family: "Inter";
      font-size: 14px;
      font-weight: 400;
      overflow: elide;
      vertical-alignment: center;
    }
  }
}
