// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component TextLabel inherits Rectangle {
  in property <string> text;

  background: #1e1e2e;
  border-radius: 4px;
  border-width: 1px;
  border-color: #18182040;
  drop-shadow-blur: 8px;
  drop-shadow-color: rgba(0, 0, 0, 0.15);
  drop-shadow-offset-y: 4px;

  HorizontalLayout {
    spacing: 8px;
    padding-left: 12px;
    padding-right: 12px;

    Text {
      text: root.text;
      color: white;
      opacity: 65%;
      font-family: "Inter";
      font-size: 14px;
      font-weight: 400;
      overflow: elide;
      vertical-alignment: center;
    }
  }
}
