// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

export component TextInput inherits Rectangle {
  in property <string> placeholder_text;
  in-out property <string> text;
  out property <bool> has_focus: input.has-focus;
  callback changed(string);

  border-width: 1px;
  border-color: root.has_focus ? #27273a : #18182040;
  background: #1e1e2e;
  clip: true;
  drop-shadow-blur: 8px;
  drop-shadow-color: rgba(0, 0, 0, 0.15);
  drop-shadow-offset-y: 4px;

  HorizontalLayout {
    padding-left: 12px;
    padding-right: 12px;
    spacing: 8px;

    input := TextInput {
      single-line: true;
      font-family: "Inter";
      font-size: 14px;
      font-weight: 400;
      color: white;
      opacity: 65%;
      vertical-alignment: center;
      text: root.text;

      if (self.text == ""): Text {
        x: 0;
        text: root.placeholder_text;
        color: #ffffff80;
        font-family: "Inter";
        font-size: 14px;
        font-weight: 400;
        opacity: 50%;
      }

      edited => {
        root.text = self.text;
        root.changed(self.text);
      }
    }
  }
}
