// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { Button } from "../components/button.slint";
import { AppLogic } from "../logic/app.slint";

export component About {
  width: 100%;
  height: 100%;

  VerticalLayout {
    alignment: start;
    spacing: 24px;
    padding: 24px;

    Rectangle { height: 1px; background: #45475a; }

    VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Text {
          text: "Application Info";
          color: #cdd6f4;
          font-size: 18px;
          font-weight: 600;
          font-family: "Inter";
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        padding-left: 36px;
        spacing: 12px;

        Text {
          text: "Aletheia is an open-source game save backup tool";
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        Text {
          text: "Version: " + AppLogic.version;
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        Text {
          text: "License: AGPL-3.0";
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        Text {
          text: "Logo by: @clanps:usesarchbtw.lol";
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        HorizontalLayout {
          spacing: 12px;
          padding-top: 8px;

          Button {
            text: "View Source Code";
            width: 180px;
            height: 38px;
            clicked => { AppLogic.open_url("https://github.com/Spencer-0003/aletheia"); }
          }

          Button {
            text: "View License";
            width: 180px;
            height: 38px;
            clicked => { AppLogic.open_url("https://github.com/Spencer-0003/aletheia/blob/master/LICENSE"); }
          }

          Button {
            text: "Support the Project";
            width: 180px;
            height: 38px;
            clicked => { AppLogic.open_url("https://github.com/Spencer-0003/aletheia?tab=readme-ov-file#support-the-project") }
          }
        }
      }
    }

    Rectangle { height: 1px; background: #45475a; }

    VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        Text {
          text: "Built with Slint";
          color: #cdd6f4;
          font-size: 18px;
          font-weight: 600;
          font-family: "Inter";
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        padding-left: 36px;
        spacing: 12px;

        Text {
          text: "Slint is a declarative GUI toolkit to build native user interfaces for Rust, C++, or JavaScript apps.";
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
          wrap: word-wrap;
        }

        HorizontalLayout {
          padding-top: 8px;

          Button {
            text: "Learn more about Slint";
            width: 180px;
            height: 38px;
            clicked => { AppLogic.open_url("https://slint.dev"); }
          }
        }
      }
    }
  }
}
