// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { Button } from "../components/button.slint";
import { AppLogic } from "../logic/app.slint";
import { ThemeLogic } from "../logic/theme.slint";

export component About {
  width: 100%;
  height: 100%;

  VerticalLayout {
    spacing: 24px;
    padding: 24px;
    alignment: start;

    VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Rectangle {
          width: 24px;
          height: 24px;

          Image {
            width: 100%;
            height: 100%;
            source: @image-url("../assets/info.svg");
            colorize: ThemeLogic.colors.text_secondary;
          }
        }

        Text {
          text: @tr("Application Info");
          color: ThemeLogic.colors.text_secondary;
          font-family: "Inter";
          font-size: 18px;
          font-weight: 600;
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        spacing: 12px;
        padding-left: 36px;

        Text {
          text: @tr("Aletheia is an open-source game save backup tool");
          color: ThemeLogic.colors.text_tertiary;
          font-family: "Inter";
          font-size: 14px;
        }

        Text {
          text: @tr("Version: {}", AppLogic.version);
          color: ThemeLogic.colors.text_tertiary;
          font-family: "Inter";
          font-size: 14px;
        }

        Text {
          text: @tr("License: {}", "AGPL-3.0");
          color: ThemeLogic.colors.text_tertiary;
          font-family: "Inter";
          font-size: 14px;
        }

        Text {
          text: @tr("Logo by: {}", "@clanps:usesarchbtw.lol");
          color: ThemeLogic.colors.text_tertiary;
          font-family: "Inter";
          font-size: 14px;
        }

        HorizontalLayout {
          spacing: 12px;
          padding-top: 8px;

          Button {
            width: 180px;
            height: 38px;
            text: @tr("View Source Code");
            clicked => AppLogic.open_url("https://github.com/Spencer-0003/aletheia");
          }

          Button {
            width: 180px;
            height: 38px;
            text: @tr("View License");
            clicked => AppLogic.open_url("https://github.com/Spencer-0003/aletheia/blob/master/LICENSE");
          }

          Button {
            width: 180px;
            height: 38px;
            text: @tr("Support the Project");
            clicked => AppLogic.open_url("https://github.com/Spencer-0003/aletheia?tab=readme-ov-file#support-the-project");
          }
        }
      }
    }
  }
}
