import { ScrollView } from "std-widgets.slint";
import { GameCard } from "../components/game_card.slint";
import { SearchBar } from "../components/search_bar.slint";
import { UiGame } from "../structs/ui_game.slint";

export global BackupScreenLogic {
  in property <[UiGame]> filtered_games: [];
  callback filter(string);
}

export component Backup {
  in property <[UiGame]> games: [];
  callback search_changed(string);
  width: 50%;
  height: 100%;

  VerticalLayout {
    spacing: 16px;

    Text {
      text: @tr("Select games to backup");
      font-size: 20px;
      font-weight: 500;
    }

    SearchBar {
      placeholder-text: @tr("Search games...");
      changed(text) => { BackupScreenLogic.filter(text); }
    }

    ScrollView {
      width: 100%;
      height: 100%;

      VerticalLayout {
        spacing: 8px;

        for game in BackupScreenLogic.filtered_games: GameCard { game: game; }
      }
    }
  }
}
