// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { GameLogic } from "../app_logic.slint";
import { Button } from "../components/button.slint";
import { GameCard } from "../components/game_card.slint";
import { SearchBar } from "../components/search_bar.slint";
import { UiGame } from "../structs/ui_game.slint";

export global BackupScreenLogic {
  in property <[UiGame]> filtered_games: [];
  callback filter(string);
}

export component Backup {
  callback search_changed(string);
  width: 50%;
  height: 100%;

  if (GameLogic.games.length == 0): VerticalLayout {
    alignment: center;
    spacing: 16px;

    Text {
      text: @tr("No games found");
      font-size: 20px;
      font-weight: 600;
      horizontal-alignment: center;
    }

    HorizontalLayout {
      alignment: center;

      Button {
        text: @tr("Refresh");
        height: 40px;
        width: 160px;
        clicked => { GameLogic.refresh_games(); }
      }
    }
  }

  if (GameLogic.games.length > 0): VerticalLayout {
    padding: 16px;
    spacing: 16px;

    Text {
      text: @tr("Select games to backup");
      font-size: 20px;
      font-weight: 500;
    }

    SearchBar {
      placeholder-text: @tr("Search games...");
      changed(text) => { BackupScreenLogic.filter(text); }
    }

    ScrollView {
      width: 100%;
      vertical-stretch: 1;

      VerticalLayout {
        spacing: 8px;

        for game in BackupScreenLogic.filtered_games: GameCard { game: game; }
      }
    }

    HorizontalLayout {
      alignment: center;
      spacing: 16px;

      Button {
        width: 140px;
        height: 36px;
        text: "Backup";
      }
    }
  }
}
