// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { Button } from "../components/button.slint";
import { GameCard } from "../components/game_card.slint";
import { SearchBar } from "../components/search_bar.slint";
import { GameLogic } from "../logic/game.slint";
import { NotificationLogic } from "../logic/notification.slint";
import { UiGame } from "../structs/ui_game.slint";

export global GamesScreenLogic {
  in property <[UiGame]> filtered_games: [];
  in property <bool> all_filtered_selected: false;
  in-out property <[UiGame]> selected_games: [];
  callback filter(string);
  callback select_all(bool);
  callback select_game(UiGame);
  callback perform_operation(string);
}

export component Games {
  width: 100%;
  height: 100%;

  if (GameLogic.games.length == 0): VerticalLayout {
    spacing: 16px;
    alignment: center;

    Text {
      text: @tr("No games found");
      color: white;
      font-family: "Inter";
      font-size: 20px;
      font-weight: 600;
      horizontal-alignment: center;
    }

    HorizontalLayout {
      alignment: center;

      Button {
        width: 160px;
        height: 40px;
        text: @tr("Refresh");
        clicked => { GameLogic.refresh_games(); }
      }
    }
  }

  if (GameLogic.games.length > 0): VerticalLayout {
    spacing: 8px;
    padding: 16px;
    alignment: start;

    HorizontalLayout {
      alignment: center;

      search_bar := SearchBar {
        width: 430px;
        height: 45px;
        placeholder-text: @tr("Search games...");
        changed(text) => { GamesScreenLogic.filter(text); }
      }
    }

    if (GamesScreenLogic.selected_games.length > 0): Text {
      text: @tr("Selecting ") + GamesScreenLogic.selected_games.length +
            " / " +
            GameLogic.games.length +
            @tr(" games");
      color: white;
      opacity: 50%;
      font-family: "Inter";
      horizontal-alignment: center;
    }

    HorizontalLayout {
      spacing: 8px;
      alignment: center;

      Button {
        width: 140px;
        height: 36px;
        text: @tr("Backup");
        enabled: GamesScreenLogic.selected_games.length > 0;
        clicked => { GamesScreenLogic.perform_operation("backup"); }
      }

      Button {
        width: 140px;
        height: 36px;
        text: @tr("Restore");
        enabled: GamesScreenLogic.selected_games.length > 0;
        clicked => { GamesScreenLogic.perform_operation("restore"); }
      }

      Button {
        width: 140px;
        height: 36px;
        text: search_bar.text.is-empty
              ? GamesScreenLogic.all_filtered_selected ? @tr("Clear Selection") : @tr("Select All")
              : @tr("{} Filtered", GamesScreenLogic.all_filtered_selected ? "Clear" : "Select");
        background: #2f2f49;
        enabled: GamesScreenLogic.filtered_games.length > 0;
        clicked => { GamesScreenLogic.select_all(!GamesScreenLogic.all_filtered_selected); }
      }
    }

    Flickable {
      VerticalLayout {
        width: 50%;
        spacing: 8px;

        for game in GamesScreenLogic.filtered_games: GameCard {
          game: game;
          clicked => {
            game.selected = !game.selected;
            GamesScreenLogic.select_game(game);
          }
        }
      }
    }
  }
}
