import { Button } from "../components/button.slint";
import { TextLabel } from "../components/text_label.slint";
import { Config } from "../structs/config.slint";

export global SettingsScreenLogic {
  in property <Config> config;
  callback browse();
  callback save_config(Config);
}

export component Settings {
  width: 100%;
  height: 100%;

  VerticalLayout {
    alignment: start;
    spacing: 24px;
    padding: 24px;

    Rectangle { height: 1px; background: #45475a; }

    VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Rectangle {
          width: 24px;
          height: 24px;
          Image {
            source: @image-url("../assets/folder.svg");
            width: 100%;
            height: 100%;
          }
        }

        Text {
          text: "Game Data Location";
          font-size: 18px;
          font-weight: 600;
          font-family: "Inter";
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        padding-left: 36px;
        spacing: 12px;

        Text {
          text: "Choose where your games will be saved";
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        HorizontalLayout {
          spacing: 8px;

          TextLabel {
            height: 38px;
            width: 400px;
            text: SettingsScreenLogic.config.save_dir;
          }

          Button {
            text: "Browse";
            width: 100px;
            height: 38px;
            clicked => { SettingsScreenLogic.browse(); }
          }
        }
      }
    }

    Rectangle { height: 1px; background: #45475a; }

    HorizontalLayout {
      alignment: end;
      padding-top: 12px;
      padding-bottom: 8px;

      Button {
        text: "Save";
        width: 120px;
        height: 40px;
        clicked => { SettingsScreenLogic.save_config(SettingsScreenLogic.config); }
      }
    }
  }
}
