// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { Button } from "../components/button.slint";
import { CheckBox } from "../components/check_box.slint";
import { TextLabel } from "../components/text_label.slint";
import { Dropdown } from "../components/dropdown.slint";
import { DropdownOption } from "../structs/dropdown_option.slint";
import { Config } from "../structs/config.slint";

export global SettingsScreenLogic {
  in property <Config> config;
  in property <bool> show_update_settings;
  in property <[DropdownOption]> steam_account_options;
  in property <string> previous_save_dir;
  in property <string> previous_steam_account_id;
  in property <bool> previous_check_for_updates: false;
  in property <bool> can_save: config.save_dir != previous_save_dir ||
                               config.steam_account_id != previous_steam_account_id ||
                               config.check_for_updates != previous_check_for_updates;
  callback browse();
  callback get_steam_users();
  callback update_gamedb();
  callback save_config(Config);
}

export component Settings {
  width: 100%;
  height: 100%;

  VerticalLayout {
    spacing: 24px;
    padding: 24px;
    alignment: start;

    Rectangle { height: 1px; background: #45475a; }

    VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Rectangle {
          width: 24px;
          height: 24px;

          Image {
            width: 100%;
            height: 100%;
            source: @image-url("../assets/folder.svg");
            colorize: #cdd6f4;
          }
        }

        Text {
          text: @tr("Game Data Location");
          color: #cdd6f4;
          font-family: "Inter";
          font-size: 18px;
          font-weight: 600;
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        spacing: 12px;
        padding-left: 36px;

        Text {
          text: @tr("Choose where your games will be saved");
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        HorizontalLayout {
          spacing: 8px;

          TextLabel {
            width: 400px;
            height: 38px;
            text: SettingsScreenLogic.config.save_dir;
          }

          Button {
            width: 100px;
            height: 38px;
            text: @tr("Browse");
            clicked => { SettingsScreenLogic.browse(); }
          }
        }
      }
    }

    Rectangle { height: 1px; background: #45475a; }

    VerticalLayout {
      z: 1; // Dropdown needs to render over other components.
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Rectangle {
          width: 24px;
          height: 24px;

          Image {
            width: 100%;
            height: 100%;
            source: @image-url("../assets/switch_account.svg");
            colorize: #cdd6f4;
          }
        }

        Text {
          text: @tr("Steam Account");
          color: #cdd6f4;
          font-family: "Inter";
          font-size: 18px;
          font-weight: 600;
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        spacing: 12px;
        padding-left: 36px;

        VerticalLayout {
          spacing: 4px;

          Text {
            text: @tr("Choose the Steam account for your games");
            color: #a6adc8;
            font-family: "Inter";
            font-size: 14px;
          }

          Text {
            text: "Only affects games that save in the Steam userdata directory";
            opacity: 25%;
            font-family: "Inter";
            font-size: 10px;
          }
        }

        Dropdown {
          width: 200px;
          height: 36px;
          options: SettingsScreenLogic.steam_account_options;
          value: SettingsScreenLogic.config.steam_account_id;
          placeholder: @tr("Select an account...");
          changed(value) => { SettingsScreenLogic.config.steam_account_id = value; }
        }
      }
    }

    Rectangle { height: 1px; background: #45475a; }

    VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Rectangle {
          width: 24px;
          height: 24px;

          Image {
            width: 100%;
            height: 100%;
            source: @image-url("../assets/database.svg");
            colorize: #cdd6f4;
          }
        }

        Text {
          text: @tr("GameDB");
          color: #cdd6f4;
          font-family: "Inter";
          font-size: 18px;
          font-weight: 600;
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        spacing: 12px;
        padding-left: 36px;

        Text {
          text: @tr("Download the latest copy of the GameDB");
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        Button {
          width: 140px;
          height: 38px;
          text: @tr("Update GameDB");
          clicked => { SettingsScreenLogic.update_gamedb(); }
        }
      }
    }

    if SettingsScreenLogic.show_update_settings: Rectangle { height: 1px; background: #45475a; }

    if SettingsScreenLogic.show_update_settings: VerticalLayout {
      spacing: 16px;

      HorizontalLayout {
        spacing: 12px;

        Rectangle {
          width: 24px;
          height: 24px;

          Image {
            width: 100%;
            height: 100%;
            source: @image-url("../assets/folder.svg");
            colorize: #cdd6f4;
          }
        }

        Text {
          text: @tr("Updates");
          color: #cdd6f4;
          font-family: "Inter";
          font-size: 18px;
          font-weight: 600;
          vertical-alignment: center;
        }
      }

      VerticalLayout {
        spacing: 12px;
        padding-left: 36px;

        Text {
          text: @tr("Configure automatic update checking");
          color: #a6adc8;
          font-family: "Inter";
          font-size: 14px;
        }

        HorizontalLayout {
          spacing: 8px;
          alignment: start;

          CheckBox {
            text: @tr("Check for updates automatically");
            enabled: SettingsScreenLogic.config.check_for_updates;
            toggled => { SettingsScreenLogic.config.check_for_updates = self.enabled; }
          }
        }
      }
    }

    Rectangle { height: 1px; background: #45475a; }

    HorizontalLayout {
      padding-top: 12px;
      padding-bottom: 8px;
      alignment: end;

      Button {
        width: 120px;
        height: 40px;
        text: @tr("Save");
        enabled: SettingsScreenLogic.can_save;
        clicked => { SettingsScreenLogic.save_config(SettingsScreenLogic.config); }
      }
    }
  }
}
