export struct Theme {
  primary: color,
  primary_hover: color,
  primary_active: color,
  primary_variant: color,

  secondary: color,
  secondary_hover: color,

  background: color,
  surface: color,
  surface_border: color,
  surface_border_alt: color,
  surface_hover: color,
  surface_selected: color,
  surface_shadow: color,
  surface_variant: color,

  text_primary: color,
  text_secondary: color,
  text_tertiary: color,
  text_muted: color,
  text_placeholder: color,

  border: color,
  border_hover: color,

  check_box_border: color,
  check_box_border_active: color,

  dropdown_shadow: color,

  updater_changelog: color,
  updater_current: color,
  updater_new: color
}
