// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { GameLogic } from "./app_logic.slint";
import { NavItem } from "./components/nav_item.slint";
import { About } from "./screens/about.slint";
import { Backup, BackupScreenLogic } from "./screens/backup.slint";
import { UiGame } from "./structs/ui_game.slint";

export { BackupScreenLogic, GameLogic }

export component App inherits Window {
  property <string> current_screen: "backup";

  preferred-width: 1280px;
  preferred-height: 900px;

  min-width: 650px;
  min-height: 500px;

  title: "Aletheia";

  Rectangle {
    background: #1e1e2e;

    VerticalLayout {
      HorizontalLayout {
        padding: 16px;
        spacing: 16px;

        NavItem {
          text: @tr("Backup");
          active: root.current_screen == "backup";
          clicked => {
            root.current_screen = "backup";
          }
        }

        NavItem {
          text: @tr("Restore");
          active: root.current_screen == "restore";
          clicked => {
            root.current_screen = "restore";
          }
        }

        NavItem {
          text: @tr("Settings");
          active: root.current_screen == "settings";
          clicked => {
            root.current_screen = "settings";
          }
        }

        NavItem {
          text: @tr("About");
          active: root.current_screen == "about";
          clicked => {
            root.current_screen = "about";
          }
        }
      }

      Rectangle {
        background: #282838;
        border-radius: 8px;
        padding: 24px;

        if (root.current_screen == "backup"): Backup {}
        if (root.current_screen == "about"): About {}
      }
    }
  }
}
