// SPDX-FileCopyrightText: 2025 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import "./fonts/Inter/InterVariable.ttf";
import "./fonts/Inter/InterVariable-Italic.ttf";
import "./fonts/Inter/Inter.ttc";

import { NavItem } from "./components/nav_item.slint";
import { Notification } from "./components/notification.slint";
import { AppLogic } from "./logic/app.slint";
import { GameLogic } from "./logic/game.slint";
import { NotificationLogic } from "./logic/notification.slint";
import { UpdaterLogic } from "./logic/updater.slint";
import { About } from "./screens/about.slint";
import { Games, GamesScreenLogic } from "./screens/games.slint";
import { Settings, SettingsScreenLogic } from "./screens/settings.slint";
import { Updater } from "./updater.slint";
import { UiGame } from "./structs/ui_game.slint";

export { AppLogic, GamesScreenLogic, GameLogic, NotificationLogic, SettingsScreenLogic }
export { Updater, UpdaterLogic }

export component App inherits Window {
  private property <string> current_screen: "games";

  preferred-width: 1280px;
  preferred-height: 900px;
  min-width: 650px;
  min-height: 500px;
  title: "Aletheia";
  icon: @image-url("../resources/logo/moe.spencer.Aletheia.png");

  Rectangle {
    background: #1e1e2e;

    VerticalLayout {
      HorizontalLayout {
        spacing: 16px;
        padding: 16px;

        NavItem {
          text: @tr("Games");
          icon: @image-url("./assets/joystick.svg");
          active: root.current_screen == "games";
          clicked => {
            if (root.current_screen != "games") {
              GamesScreenLogic.filter(""); // Lazy hack to reset search, waiting for https://github.com/slint-ui/slint/pull/6657 to be merged.
            }

            root.current_screen = "games";
          }
        }

        NavItem {
          text: @tr("Settings");
          icon: @image-url("./assets/settings.svg");
          active: root.current_screen == "settings";
          clicked => { root.current_screen = "settings"; }
        }

        NavItem {
          text: @tr("About");
          icon: @image-url("./assets/about.svg");
          active: root.current_screen == "about";
          clicked => { root.current_screen = "about"; }
        }
      }

      Rectangle {
        padding: 24px;
        background: #282838;
        border-radius: 8px;

        if (root.current_screen == "games"): Games {}
        if (root.current_screen == "settings"): Settings {}
        if (root.current_screen == "about"): About {}
      }
    }
  }

  Notification {
    y: parent.height - self.height - 20px;
    target_x: parent.width - self.width - 20px;
    visible: NotificationLogic.is_notification_visible;
    message: NotificationLogic.current_notification_message;
    notification_type: NotificationLogic.current_notification_type;

    closed => { NotificationLogic.hide_notification(); }
  }
}
