name: Unit Tests
on:
  pull_request:
    paths:
      - 'src/dirs.rs'

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: cargo test --all --locked
